/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MotivateRouteImport } from "./routes/motivate";
import { Route as MotivatesIdRouteImport } from "./routes/motivates/$id";

const MotivateRoute = MotivateRouteImport.update({
	id: "/motivate",
	path: "/motivate",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const MotivatesIdRoute = MotivatesIdRouteImport.update({
	id: "/motivates/$id",
	path: "/motivates/$id",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/motivate": typeof MotivateRoute;
	"/motivates/$id": typeof MotivatesIdRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/motivate": typeof MotivateRoute;
	"/motivates/$id": typeof MotivatesIdRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/motivate": typeof MotivateRoute;
	"/motivates/$id": typeof MotivatesIdRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/motivate" | "/motivates/$id";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/motivate" | "/motivates/$id";
	id: "__root__" | "/" | "/motivate" | "/motivates/$id";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	MotivateRoute: typeof MotivateRoute;
	MotivatesIdRoute: typeof MotivatesIdRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/motivate": {
			id: "/motivate";
			path: "/motivate";
			fullPath: "/motivate";
			preLoaderRoute: typeof MotivateRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/motivates/$id": {
			id: "/motivates/$id";
			path: "/motivates/$id";
			fullPath: "/motivates/$id";
			preLoaderRoute: typeof MotivatesIdRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	MotivateRoute: MotivateRoute,
	MotivatesIdRoute: MotivatesIdRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
